### ISSUE TITLE
System.NullReferenceException at application startup under Win8.1

### ISSUE THREAD

**Issue by MagicAndre1981** [Alois-xx/WMIWatcher#1]
Directly at start, I get this System.NullReferenceException:

```
[Success] Name WMIWatcher
[Success] ServiceName WMIWatcher
Topshelf v4.3.0.0, .NET 7.0.0 (7.0.0)
The WMIWatcher service is now running, press Control+C to exit.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at WMIWatcher.ETW.WMIStart..ctor(TraceEvent event, TraceLogEventSource realtimeSource, TraceLog log) in C:\Sourc
e\git\WMIWatcher\ETW\WMIStart.cs:line 55
   at WMIWatcher.WMIEventParser.Parse(TraceEvent data) in C:\Source\git\WMIWatcher\WMIEventParser.cs:line 77
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.DoDispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.DispatchClonedEvent(TraceEvent toSend)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.FlushRealTimeEvents(Object notUsed)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Ob
ject state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Ob
ject state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Under Windows 10 it starts and displays WMI activities.

**Comment by Alois-xx** [comment]
Try v 1.0.6.0 which should fix the issue.

**Comment by MagicAndre1981** [comment]
> Try v 1.0.6.0 which should fix the issue.

work fine now and shows WMI activity
